2021-06-02 16:59:12 co.com.japl.ea.gdb.privates.impls.ConnectionJDBC : ERROR : No se encontro el archivo de properties .//connection-jdbc.properties en ./ en path /home/alejo/git/pyt/pyt-contabilidad/./connection-jdbc.properties
2021-06-02 16:59:12 com.pyt.service.implement.UserSvc : ERROR : co.com.japl.ea.query.implement.QuerySvc
2021-06-02 16:59:12 com.pyt.service.implement.GenericServiceSvc : ERROR : co.com.japl.ea.query.implement.QuerySvc
2021-06-02 16:59:13 org.pyt.app.beans.users.LoginBean : ERROR : Null pointer exception
2021-06-02 16:59:13 org.pyt.app.beans.users.LoginBean : ERROR : When open file throw EOF exception
Error presentado en printTrace::./logger/stracTrace.log (No existe el archivo o el directorio)
2021-06-02 17:32:13 co.com.japl.ea.gdb.privates.impls.ConnectionJDBC : ERROR : No se encontro el archivo de properties .//connection-jdbc.properties en ./ en path /home/alejo/git/pyt/pyt-contabilidad/./connection-jdbc.properties
2021-06-02 17:32:13 com.pyt.service.implement.UserSvc : ERROR : co.com.japl.ea.query.implement.QuerySvc
2021-06-02 17:32:13 com.pyt.service.implement.GenericServiceSvc : ERROR : co.com.japl.ea.query.implement.QuerySvc
2021-06-02 17:32:13 org.pyt.app.beans.users.LoginBean : ERROR : Null pointer exception
2021-06-02 17:32:13 org.pyt.app.beans.users.LoginBean : ERROR : When open file throw EOF exception
2021-06-02 17:38:25 co.com.japl.ea.gdb.privates.impls.ConnectionJDBC : ERROR : No se encontro el archivo de properties .//connection-jdbc.properties en ./ en path /home/alejo/git/pyt/pyt-contabilidad/./connection-jdbc.properties
2021-06-02 17:38:25 com.pyt.service.implement.UserSvc : ERROR : co.com.japl.ea.query.implement.QuerySvc
2021-06-02 17:38:25 com.pyt.service.implement.GenericServiceSvc : ERROR : co.com.japl.ea.query.implement.QuerySvc
2021-06-02 17:38:25 org.pyt.app.beans.users.LoginBean : ERROR : Null pointer exception
2021-06-02 17:38:25 org.pyt.app.beans.users.LoginBean : ERROR : When open file throw EOF exception
